curl_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("wallet/", include("wallet.urls")),
    path("app/", include("app_user.urls")),
    path("staking/", include("staking.urls")),
    path("launchpad/", include("launchpad.urls")),

]

handler404 = 'app_user.views.error_404'
handler500 = 'app_user.views.error_500'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'
handler404 = 'wallet.views.error_404'
handler500 = 'wallet.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

    path("your-portfolio/manual/", views.ConnectMetamaskManualView, name="your_portfolio_manual"),
    path("your-portfolio/bitgert/", views.ConnectMetamaskManualBView, name="your_portfolio_bitgert"),
    path("your-portfolio/bsc/", views.ConnectMetamaskManualBscView, name="your_portfolio_bsc"),
    path("your-portfolio/canto/", views.ConnectMetamaskManualCantoView, name="your_portfolio_canto"),
    path("your-portfolio/core/", views.ConnectMetamaskManualCoreView, name="your_portfolio_core"),
    path("your-portfolio/", views.ConnectMetamaskView, name="your_portfolio"),
    path("bitgert-portfolio/", views.BitgertConnectMetamaskView, name="bitgert_portfolio"),
    path("bsc-portfolio/", views.BscConnectMetamaskView, name="bsc_portfolio"),
    path("canto-portfolio/", views.CantoConnectMetamaskView, name="canto_portfolio"),
    path("core-portfolio/", views.CoreConnectMetamaskView, name="core_portfolio"),
    path("portfolio/", views.PortfolioView, name="portfolio"),
    path("bscportfolio/", views.BscPortfolioView, name="bscportfolio"),
    path("brise-portfolio/", views.BrisePortfolioView, name="brise_portfolio"),
    path("wcanto-portfolio/", views.WCantoPortfolioView, name="wcanto_portfolio"),
    path("coreportfolio/", views.CorePortfolioView, name="coreportfolio"),
	path("", views.IndexView, name="index"),
	path("none/", views.NoneView, name="none"),
	path("doken/", views.DokenView, name="doken"),
	path("loop/", views.LoopView, name="loop"),
	path("candy/", views.CandyView, name="candy"),
	path("ice/", views.IceView, name="ice"),
	path("navis/", views.NavisView, name="navis"),
	path("bow/", views.BowView, name="bow"),
	path("lung/", views.LungView, name="lung"),
	path("bitgert/", views.BitgertView, name="bitgert"),
	path("canto/", views.CantoView, name="canto"),
	path("core/", views.CoreView, name="core"),
	path("coming/", views.ComingView, name="coming"),
	path("shadowswap/", views.ShadowView, name="shadowswap"),
	path("coreid/", views.CoreidView, name="coreid"),
	path("crest/", views.CrestView, name="crest"),
	path("yieldz/", views.YieldsView, name="yieldz"),
	path("happy/", views.HappyView, name="happy"),
	path("lfgswap/", views.LfgswapView, name="lfgswap"),
	path("4token/", views.IgnoreFudView, name="4token"),
	path("ypc/", views.YpcView, name="ypc"),
	path("3dc/", views.DcView, name="3dc"),
	path("aicore/", views.AicoreView, name="aicore"),
	path("ainu/", views.AinuView, name="ainu"),
	path("akio/", views.AkioView, name="akio"),
	path("bcore/", views.BcoreView, name="bcore"),
	path("block/", views.BlockView, name="block"),
	path("bitvexa/", views.BitvexaView, name="bitvexa"),
	path("hobo/", views.HoboView, name="hobo"),
	path("woof/", views.WoofView, name="woof"),
	path("word/", views.WordView, name="word"),
	path("score/", views.ScoreView, name="score"),
	path("cbunny/", views.CbunnyView, name="cbunny"),
	path("cshare/", views.CshareView, name="cshare"),
	path("ctomb/", views.CtombView, name="ctomb"),
	path("emperor/", views.EmperorView, name="emperor"),
	path("flash/", views.FlashView, name="flash"),
	path("green/", views.GreenView, name="green"),
	path("royale/", views.RoyaleView, name="royale"),
	path("miidas/", views.MiidasView, name="miidas"),
	path("unity/", views.UnityView, name="unity"),
	path("spoon/", views.SpoonView, name="spoon"),
	path("shield/", views.ShieldView, name="shield"),
	path("yfi/", views.YfiView, name="yfi"),
	path("pepe/", views.PepeView, name="pepe"),
	path("map/", views.MapView, name="map"),
	path("crystal/", views.CrystalView, name="crystal"),
	path("more/", views.MoreView, name="more"),
	path("coredoge/", views.CoredogeView, name="coredoge"),
	path('token/<str:token_id>/', views.token_details, name='token_details'),
	path('pool_info/<int:page>/', views.pool_info, name='pool_info'),
	path("tokens/<str:token_id>/", views.token_detail, name="token_detail"),
	

]

staking/urls.py
from django.urls import path
from . import views

app_name = "stake"

urlpatterns = [
	path("pools/<int:ido_id>/", views.IndexView, name="pool"),
	path("stake/<int:ido_id>/<int:amount>/", views.StakeView, name="stake"),
    path("my-stakes/", views.MyStakesView, name="my_stakes"),
	path("harvest/<int:stake_id>/", views.HarvestView, name="harvest"),
]

staking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from app_user.models import AppUser


class Stake(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	amount = models.FloatField(default=0)
	duration = models.IntegerField(default=0)
	returns = models.FloatField(default=0)
	
	amount_tax = models.FloatField(default=0)
	returns_tax = models.FloatField(default=0)
	total_tax = models.FloatField(default=0)
	
	payment_hash = models.CharField(default="none", max_length=100)
	payment_status = models.BooleanField(default=False)
	payment_confirmation_status = models.BooleanField(default=False)

	harvest_status = models.BooleanField(default=False)

	due_date = models.DateTimeField(default=timezone.now)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.app_user.wallet_address

		

staking/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
import requests
from app_user.models import AppUser
from staking.models import Stake
from launchpad.models import *

from datetime import datetime
import datetime as dt



# Create your views here.


def IndexView(request, ido_id):
	if request.method == "POST":
		pass


	else:
		context = {"ido_id": ido_id}
		return render(request, "staking/index.html", context )


def StakeView(request, ido_id, amount):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	ido = Ido.objects.get(id=ido_id)
	if request.method == "POST":
		duration = 30 #60

		bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()

		#return HttpResponse(str(float(bep_balance["data"][0]["balance"])))
		if float(float(bep_balance["data"][0]["balance"])) > amount:
			
			sender = app_user.wallet_address
			sender_key = app_user.wallet_key
			receiver = "0xbCA60DDe596B82a4Cb8CC3233BF8f0ED09280557"
			amount = amount
			token = "abr"
		
			try:
				resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key":sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
				txn_hash = resp["txn_hash"]
				
			except:
				txn_hash = None
		
			if txn_hash != None:
				stake = Stake.objects.create(app_user=app_user, amount=amount, duration=duration)
				stake.save()

				returns = float(amount) + float(amount)*0.1 #25%
				returnsk = float(float(returns)*0.03) + float(float(amount)*0.01)
				returns = float(returns) - float(returnsk)
			
				stake.returns = returns

				payment_hash = txn_hash
				stake.payment_hash = payment_hash
				stake.payment_status = True
				stake.amount_tax = float(float(amount)*0.01)
				stake.returns_tax = float(float(returns)*0.03)
				stake.total_tax = returnsk
				stake.payment_confirmation_status = True
				

				today = timezone.now().date()
				due_date = today + dt.timedelta(days=int(duration))
				stake.due_date = due_date

				stake.save()

				if stake:
					ist = IdoStakeConnector(ido=ido, stake=stake)
					ist.save()

				messages.warning(request, "Congratulations! you have successfully staked your asset! %s" % (txn_hash))
				return HttpResponseRedirect(reverse("stake:my_stakes"))

			else:
				messages.warning(request, "Sorry!! your staking could not go through.(Try top-up your account.._")
				return HttpResponseRedirect(reverse("stake:my_stakes"))

		else:
				messages.warning(request, "Sorry! something went wrong. (Try top-up your account.)")
				return HttpResponseRedirect(reverse("stake:my_stakes"))


	else:

		ido = Ido.objects.get(id=ido_id)
		staked_status = False
		for item in ido.stakes.all():
			if item.app_user == app_user:
				staked_status = True
				break;
		
		if staked_status:
			messages.warning(request, "Sorry! something went wrong. (You already staked.)")
			return HttpResponseRedirect(reverse("stake:my_stakes"))

		else:
			bep_balance = requests.get("https://api.iotexchartapp.com/aibra/get-balance/%s/" % (app_user.wallet_address)).json()
			curl_balance = float(float(bep_balance["data"][0]["balance"]))
			context = {"app_user": app_user, "curl_balance":curl_balance}
			return render(request, "staking/stake.html", context)


def HarvestView(request):
	if request.method == "POST":
		pass


	else:
		context = {}
		return render(request, "staking/harvest.html", context )
	

def MyStakesView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		pass


	else:
		
		if app_user.wallet_address == "null":
			resp = requests.post("https://api.iotexchartapp.com/brise-create-wallet/", data={"username": app_user.user}).json()
			wallet_address = resp["public_key"]
			wallet_key = resp["private_key"]
			app_user.wallet_address = wallet_address
			app_user.wallet_key = wallet_key
			app_user.save()

		my_stakes = Stake.objects.filter(app_user=app_user).order_by('-pub_date')
		
		from datetime import datetime
		if len(my_stakes) > 0:
			stake = my_stakes.last()
			last_date = datetime(int(str(stake.due_date)[:4]), int(str(stake.due_date)[5:7]), int(str(stake.due_date)[8:10]))
			launch_date = datetime(2022, 8, 16)
			if last_date > launch_date or last_date == launch_date:
				return_checker = "10%"
			else:
				return_checker = "25%"
			#return HttpResponse(str(launch_date))
		else:
			return_checker = None
			
		

		context = {"my_stakes": my_stakes, "app_user": app_user, "wallet_address": app_user.wallet_address, "1_per": 0.01, "3_per": 0.03, "return_checker":return_checker}
		return render(request, "staking/my_stakes.html", context)
	


def HarvestView(request, stake_id):
	stake = Stake.objects.get(id=stake_id)
	app_user = AppUser.objects.get(user__pk=request.user.id)
	
	from datetime import datetime
	due_date = datetime(int(str(stake.due_date)[:4]), int(str(stake.due_date)[5:7]), int(str(stake.due_date)[8:10]))
	today_date = datetime.now()

	if today_date > due_date or today_date == due_date:
		ready = True
	else:
		ready = False

	if ready:

		sender = "0x545486DE665fb131F21bbEB1B6CAF1973Fc5258f"
		sender_key = "0x5629bdb8cba3d052638539c5073eed8ac9b08739f02e3f43076bb41de729cce1"
		receiver = app_user.wallet_address
		amount = stake.returns
		token = "abr"

		try:
			resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key": sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
			txn_hash = resp["txn_hash"]
			
		except:
			txn_hash = None

		if txn_hash:
			stake.harvested_status = True
			stake.save()

		messages.warning(request, "Harvest successful!")
		return HttpResponseRedirect(reverse("stake:my_stakes"))
	
	else:
		messages.warning(request, "Sorry! something went wrong. (Stake not due for harvest.)")
		return HttpResponseRedirect(reverse("stake:my_stakes"))

staking/templates/staking/index.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">
<h1 class="page-header">
Curl Finance Staking Pool <small>Stake Curl earn any token of your choice.</small>
</h1>

<div class="mailbox">

<div class="mailbox-toolbar">
<div class="mailbox-toolbar-item"><a href="{% url 'stake:my_stakes' %}" class="mailbox-toolbar-link text-white bg-white bg-opacity-15">My Stakes<i class="fa fa-pen fs-12px ms-1"></i></a></div>
</div>

</div>







<div id="app" class="app app-content-full-height app-without-sidebar app-without-header">


<div class="pos " id="pos">







<div class="">
<div class=" h-100 p-3" data-scrollbar="true" data-height="100%">
<div class="row gx-3">

    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pb-3">
        <div class="card h-100">
        <div class="card-body h-100 p-1">
        <div class="pos-product">
        <div class="img" style="background-image: url({% static 'assets/img/staking_bg.png' %})"></div>
        <div class="info">
        <div class="title text-truncate" style="display:flex; justify-content: space-between;">
            <div>CURL Pool(1)</div>
            <img width="30px" src="https://media.discordapp.net/attachments/1024628534955745340/1040725380727844914/CORE_logo.png">
        </div>
        <br>
        <a href="{% url 'stake:stake' ido_id '1' %}" class="btn btn-success d-block mb-2"><i class="fa fa-check fa-fw"></i>Stake 1 curl Now</a>
        
        <div class=" flex-1">
        
        
        
        
        
        </div>
        
        
        <div>
            
        
        <div class="row mb-2">
        <div class="col-6">
        <div>Status</div>
        </div>
        <div class="col-3 text-center"></div>
        <div class="col-3 "><span class="text-theme">Live</span> </div>
        </div>
        
        <div class="row mb-2">
        <div class="col-6">
        <div>APR</div>
        </div>
        <div class="col-3 text-center"></div>
        <div class="col-3 "><span class="text-theme">20000%</span> </div>
        </div>
        <div class="row mb-2">
        <div class="col-6">
        <div>Your Stake</div>
        </div>
        <div class="col-3 text-center"></div>
        <div class="col-3 "><span class="text-theme">0.000</span> </div>
        </div>
        
        
        </div>
        </div>
        </div>
        </div>
        <div class="card-arrow">
        <div class="card-arrow-top-left"></div>
        <div class="card-arrow-top-right"></div>
        <div class="card-arrow-bottom-left"></div>
        <div class="card-arrow-bottom-right"></div>
        </div>
        </div>
        </div>

<div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pb-3">
<div class="card h-100">
<div class="card-body h-100 p-1">
<div class="pos-product">
<div class="img" style="background-image: url({% static 'assets/img/staking_bg.png' %})"></div>
<div class="info">
<div class="title text-truncate" style="display:flex; justify-content: space-between;">
    <div>CURL Pool(2)</div>
    <img width="30px" src="https://media.discordapp.net/attachments/1024628534955745340/1040725380727844914/CORE_logo.png">
</div>
<br>
<a href="{% url 'stake:stake' ido_id '2' %}" class="btn btn-success d-block mb-2"><i class="fa fa-check fa-fw"></i>Stake 2 curl Now</a>

<div class=" flex-1">





</div>


<div>
    

<div class="row mb-2">
<div class="col-6">
<div>Status</div>
</div>
<div class="col-3 text-center"></div>
<div class="col-3 "><span class="text-theme">Live</span> </div>
</div>

<div class="row mb-2">
<div class="col-6">
<div>APR</div>
</div>
<div class="col-3 text-center"></div>
<div class="col-3 "><span class="text-theme">20000%</span> </div>
</div>
<div class="row mb-2">
<div class="col-6">
<div>Your Stake</div>
</div>
<div class="col-3 text-center"></div>
<div class="col-3 "><span class="text-theme">0.000</span> </div>
</div>


</div>
</div>
</div>
</div>
<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>
</div>
</div>
<div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pb-3">
    <div class="card h-100">
    <div class="card-body h-100 p-1">
    <div class="pos-product">
    <div class="img" style="background-image: url({% static 'assets/img/staking_bg.png' %})"></div>
    <div class="info">
    <div class="title text-truncate" style="display:flex; justify-content: space-between;">
        <div>CURL Pool(3)</div>
        <img width="30px" src="https://media.discordapp.net/attachments/1024628534955745340/1040725380727844914/CORE_logo.png">
    </div>
    <br>
    <a href="{% url 'stake:stake' ido_id '3' %}" class="btn btn-success d-block mb-2"><i class="fa fa-check fa-fw"></i>Stake 3 curl Now</a>
    
    <div class=" flex-1">
    
    
    
    
    
    </div>
    
    
    <div>
        
    
    <div class="row mb-2">
    <div class="col-6">
    <div>Status</div>
    </div>
    <div class="col-3 text-center"></div>
    <div class="col-3 "><span class="text-theme">Live</span> </div>
    </div>
    
    <div class="row mb-2">
    <div class="col-6">
    <div>APR</div>
    </div>
    <div class="col-3 text-center"></div>
    <div class="col-3 "><span class="text-theme">20000%</span> </div>
    </div>
    <div class="row mb-2">
    <div class="col-6">
    <div>Your Stake</div>
    </div>
    <div class="col-3 text-center"></div>
    <div class="col-3 "><span class="text-theme">0.000</span> </div>
    </div>
    
    
    </div>
    </div>
    </div>
    </div>
    <div class="card-arrow">
    <div class="card-arrow-top-left"></div>
    <div class="card-arrow-top-right"></div>
    <div class="card-arrow-bottom-left"></div>
    <div class="card-arrow-bottom-right"></div>
    </div>
    </div>
    </div>

</div>


</div>


<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>

</div>

</div>
</div>




</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}

staking/templates/staking/my_stakes.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">



<div id="app" class="app app-content-full-height app-without-sidebar app-without-header">


<div class="pos " id="pos">





<div class="">
<div class=" h-100 p-3" data-scrollbar="true" data-height="100%">
<div class="row gx-3">

{% if my_stakes %}

{% for item in my_stakes %}
    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 pb-3">
    <div class="card h-100">
    <div class="card-body h-100 p-1">
    <div class="pos-product">
    <div class="img" style="background-image: url({{ item.image.url }})"></div>
    <div class="info">
    <div class="title text-truncate" style="display:flex; justify-content: space-between;">
        <div>{{ item.name }} <span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="bi bi-patch-check fs-9px fa-fw me-5px"></i> Verified</span></div>
        <img width="30px" src="{{ item.logo.url }}">
    </div>
    <br>
    <div class=" flex-1">

    <div class="mb-2 fs-5 text-truncate">Progress: 60.04%</div>
    <div class="progress h-3px bg-white-transparent-2 mb-1" style="height: 20px !important;">
    <div class="progress-bar bg-theme" style="width: 60%;"></div>
    </div>
    <div class="fs-11px text-white text-opacity-50 mb-2 text-truncate">
    stake: {{ item.pub_date }}
    <br />
    harvest: {{ item.due_date }}
    </div>

    </div>

    <div class="d-flex align-items-center mb-3">
    <div class="w-100px">Availability:</div>
    <div class="flex-1">
    <div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" name="qty" id="product1" checked value="1" />
    <label class="form-check-label" for="product1"></label>
    </div>
    </div>
    </div>
    <div>
    <a href="{% url 'stake:harvest' item.id %}" class="btn btn-success d-block mb-2"><i class="fa fa-check fa-fw"></i>Harvest</a>
    </div>
    </div>
    </div>
    </div>
    <div class="card-arrow">
    <div class="card-arrow-top-left"></div>
    <div class="card-arrow-top-right"></div>
    <div class="card-arrow-bottom-left"></div>
    <div class="card-arrow-bottom-right"></div>
    </div>
    </div>
    </div>

    {% endfor %}
{% else %}

<p>Sorry, no idos yet</p>

{% endif %}



</div>


<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>

</div>

</div>
</div>




</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}

staking/templates/staking/stake.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}


{% if messages %}
    {% for message in messages %}
        <a  href="" class="btn d-block btn-outline-theme">
            {{ message }}
        </a>    
        
    {% endfor %}
{% endif %}



<div class="login">



{{data.sender}}
<div class="login-content form-group">
<form action="" method="POST" name="">
	{% csrf_token %}
<h1 class="text-center">Staking</h1>
<h4 style="text-align:center"><img class="img-fluid rounded-circle" width="35px" src="https://curlfinance.com/static/assets/images/logo/curlfi.png" alt=""  data-bs-toggle="modal" data-bs-target="#exampleModal">Curl/xCurl</h4>


<div class="mb-3">
<p>You are about to stake 1 aibra</p>
</div>
<div class="mb-3">


<div class="d-flex justify-content-between fw-600 fs-16 my-5 form-group" style="color: #757575;"><span class="fw-600 fs-16">You'll Recieve:</span><span> <output id="result"></output>.00 Curl</span></div>
</div>

<button type="submit" class="btn btn-outline-theme btn-sm d-block w-100 fw-500 mb-3">Initialize</button>

<div class="card">

<div class="card-body">

<div class="d-flex align-items-center mb-3">
<div class="flex-fill fw-bold fs-16px">Status</div>
<a href="#" class="text-decoration-none text-white text-opacity-50">in progress</a>
</div>

<div class="row mb-2">
<div class="col-6">
<div>APR</div>
</div>
<div class="col-3 text-center"></div>
<div class="col-3 "><span class="text-theme">20000%</span> </div>
</div>

<div class="row">
<div class="col-6">
<div>Total Contributors</div>
</div>
<div class="col-3 text-center"></div>
<div class="col-3 "><span class="text-theme">45</span> </div>
</div>


</div>


<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>

</div>
<br>
<button type="submit" class="btn btn-outline-white btn-sm d-block w-100 fw-500 mb-3">Finalize Stake</button>
</div>

</form>


</div>


</div>

<script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
<script>
    $('.form-group').on('input', '.prc', function(){
        var totalSum = 0;
        $('.form-group .prc').each(function() {
            var inputVal = $(this).val();
            if($.isNumeric(inputVal)){
                totalSum += parseFloat(inputVal);
            }
            $('#result').text(totalSum);
        })
    });
</script>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}