curl_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("wallet/", include("wallet.urls")),
    path("app/", include("app_user.urls")),
    path("staking/", include("staking.urls")),
    path("launchpad/", include("launchpad.urls")),

]

handler404 = 'app_user.views.error_404'
handler500 = 'app_user.views.error_500'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'
handler404 = 'wallet.views.error_404'
handler500 = 'wallet.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

    path("your-portfolio/manual/", views.ConnectMetamaskManualView, name="your_portfolio_manual"),
    path("your-portfolio/bitgert/", views.ConnectMetamaskManualBView, name="your_portfolio_bitgert"),
    path("your-portfolio/bsc/", views.ConnectMetamaskManualBscView, name="your_portfolio_bsc"),
    path("your-portfolio/canto/", views.ConnectMetamaskManualCantoView, name="your_portfolio_canto"),
    path("your-portfolio/core/", views.ConnectMetamaskManualCoreView, name="your_portfolio_core"),
    path("your-portfolio/", views.ConnectMetamaskView, name="your_portfolio"),
    path("bitgert-portfolio/", views.BitgertConnectMetamaskView, name="bitgert_portfolio"),
    path("bsc-portfolio/", views.BscConnectMetamaskView, name="bsc_portfolio"),
    path("canto-portfolio/", views.CantoConnectMetamaskView, name="canto_portfolio"),
    path("core-portfolio/", views.CoreConnectMetamaskView, name="core_portfolio"),
    path("portfolio/", views.PortfolioView, name="portfolio"),
    path("bscportfolio/", views.BscPortfolioView, name="bscportfolio"),
    path("brise-portfolio/", views.BrisePortfolioView, name="brise_portfolio"),
    path("wcanto-portfolio/", views.WCantoPortfolioView, name="wcanto_portfolio"),
    path("coreportfolio/", views.CorePortfolioView, name="coreportfolio"),
	path("", views.IndexView, name="index"),
	path("none/", views.NoneView, name="none"),
	path("doken/", views.DokenView, name="doken"),
	path("loop/", views.LoopView, name="loop"),
	path("candy/", views.CandyView, name="candy"),
	path("ice/", views.IceView, name="ice"),
	path("navis/", views.NavisView, name="navis"),
	path("bow/", views.BowView, name="bow"),
	path("lung/", views.LungView, name="lung"),
	path("bitgert/", views.BitgertView, name="bitgert"),
	path("canto/", views.CantoView, name="canto"),
	path("core/", views.CoreView, name="core"),
	path("coming/", views.ComingView, name="coming"),
	path("shadowswap/", views.ShadowView, name="shadowswap"),
	path("coreid/", views.CoreidView, name="coreid"),
	path("crest/", views.CrestView, name="crest"),
	path("yieldz/", views.YieldsView, name="yieldz"),
	path("happy/", views.HappyView, name="happy"),
	path("lfgswap/", views.LfgswapView, name="lfgswap"),
	path("4token/", views.IgnoreFudView, name="4token"),
	path("ypc/", views.YpcView, name="ypc"),
	path("3dc/", views.DcView, name="3dc"),
	path("aicore/", views.AicoreView, name="aicore"),
	path("ainu/", views.AinuView, name="ainu"),
	path("akio/", views.AkioView, name="akio"),
	path("bcore/", views.BcoreView, name="bcore"),
	path("block/", views.BlockView, name="block"),
	path("bitvexa/", views.BitvexaView, name="bitvexa"),
	path("hobo/", views.HoboView, name="hobo"),
	path("woof/", views.WoofView, name="woof"),
	path("word/", views.WordView, name="word"),
	path("score/", views.ScoreView, name="score"),
	path("cbunny/", views.CbunnyView, name="cbunny"),
	path("cshare/", views.CshareView, name="cshare"),
	path("ctomb/", views.CtombView, name="ctomb"),
	path("emperor/", views.EmperorView, name="emperor"),
	path("flash/", views.FlashView, name="flash"),
	path("green/", views.GreenView, name="green"),
	path("royale/", views.RoyaleView, name="royale"),
	path("miidas/", views.MiidasView, name="miidas"),
	path("unity/", views.UnityView, name="unity"),
	path("spoon/", views.SpoonView, name="spoon"),
	path("shield/", views.ShieldView, name="shield"),
	path("yfi/", views.YfiView, name="yfi"),
	path("pepe/", views.PepeView, name="pepe"),
	path("map/", views.MapView, name="map"),
	path("crystal/", views.CrystalView, name="crystal"),
	path("more/", views.MoreView, name="more"),
	path("coredoge/", views.CoredogeView, name="coredoge"),
	path('token/<str:token_id>/', views.token_details, name='token_details'),
	path('pool_info/<int:page>/', views.pool_info, name='pool_info'),
	path("tokens/<str:token_id>/", views.token_detail, name="token_detail"),
	

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea, TextInput, Select
from django.utils import timezone


# Create your models here.

class Unvetted(models.Model):
    token_address = models.CharField(max_length=120)
    telegram_url = models.CharField(max_length=120)
    #image = models.ImageField(upload_to='media')
    #proof_of_payment = models.CharField(max_length=200, blank=True, default=None)
    pub_date = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.token_address


class Banner(models.Model):
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=500)
    link = models.CharField(max_length=100)
    #image = models.ImageField(upload_to='media')
    company_name = models.CharField(max_length=100)
    interest = models.CharField(max_length=200)
    budget = models.CharField(max_length=100)
    proof_of_payment = models.CharField(max_length=100)
    about_project = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

main/views.py
from django.contrib import messages
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                            get_object_or_404, redirect, render)
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required




from django.core.mail import send_mail

from datetime import datetime
import datetime as dt
import requests

#from .forms import UserForm

from datetime import datetime
from requests import Request, Session
import json
import time
from datetime import datetime, timedelta


import asyncio
import requests



async def DekatronCoredao():
    coredao = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x40375C92d9FAf44d2f9db9Bd9ba41a3317a2404f")
            
    coredaodekatron = coredao.json()
    coredaopairs = coredaodekatron["pairs"][0]
    coredaobaseToken = coredaopairs["baseToken"]
    coredaopriceNative = coredaopairs["priceNative"]
    coredaopriceUsd = coredaopairs["priceUsd"]
    coredaovolume = coredaopairs["volume"]
    coredaopriceChange = coredaopairs["priceChange"]
    coredaofdv = coredaopairs["fdv"]

    return coredaobaseToken, coredaopriceNative, coredaopriceUsd, coredaovolume, coredaopriceChange, coredaofdv

async def DekatronIce():
    ice = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xb999ea90607a826a3e6e6646b404c3c7d11fa39d")
    icedekatron = ice.json()
    icepairs = icedekatron["pairs"][0]
    icebaseToken = icepairs["baseToken"]
    icepriceNative = icepairs["priceNative"]
    icepriceUsd = icepairs["priceUsd"]
    icevolume = icepairs["volume"]
    icepriceChange = icepairs["priceChange"]
    icefdv = icepairs["fdv"]

    return icebaseToken, icepriceNative, icepriceUsd, icevolume, icepriceChange, icefdv


async def DekatronBow():
    bow = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x1a639e150d2210A4BE4a5F0857A9151B241E7AE4")
    bowdekatron = bow.json()
    bowpairs = bowdekatron["pairs"][0]
    bowbaseToken = bowpairs["baseToken"]
    bowpriceNative = bowpairs["priceNative"]
    bowpriceUsd = bowpairs["priceUsd"]
    bowvolume = bowpairs["volume"]
    bowpriceChange = bowpairs["priceChange"]
    bowfdv = bowpairs["fdv"]

    return bowbaseToken, bowpriceNative, bowpriceUsd, bowvolume, bowpriceChange, bowfdv

async def DekatronShadow():
    shadow = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xddBa66C1eBA873e26Ac0215Ca44892a07d83aDF5")
    shadowdekatron = shadow.json()
    shadowpairs = shadowdekatron["pairs"][0]
    shadowbaseToken = shadowpairs["baseToken"]
    shadowpriceNative = shadowpairs["priceNative"]
    shadowpriceUsd = shadowpairs["priceUsd"]
    shadowvolume = shadowpairs["volume"]
    shadowpriceChange = shadowpairs["priceChange"]
    shadowfdv = shadowpairs["fdv"]
    shadowlogo = "https://shadowswap.xyz/favicon.ico"

    return shadowbaseToken, shadowpriceNative, shadowpriceUsd, shadowvolume, shadowpriceChange, shadowfdv, shadowlogo


async def DekatronCoreid():
    coreid = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x000000000e1d682cc39abe9b32285fdea1255374")
    coreiddekatron = coreid.json()
    coreidpairs = coreiddekatron["pairs"][0]
    coreidbaseToken = coreidpairs["baseToken"]
    coreidpriceNative = coreidpairs["priceNative"]
    coreidpriceUsd = coreidpairs["priceUsd"]
    coreidvolume = coreidpairs["volume"]
    coreidpriceChange = coreidpairs["priceChange"]
    coreidfdv = coreidpairs["fdv"]

    return coreidbaseToken, coreidpriceNative, coreidpriceUsd, coreidvolume, coreidpriceChange, coreidfdv



async def DekatronWoof():
    woof = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x5C44d3D2312AbA4d5F2406A98Bf374Bc76455092")
    woofdekatron = woof.json()
    woofpairs = woofdekatron["pairs"][0]
    woofbaseToken = woofpairs["baseToken"]
    woofpriceNative = woofpairs["priceNative"]
    woofpriceUsd = woofpairs["priceUsd"]
    woofvolume = woofpairs["volume"]
    woofpriceChange = woofpairs["priceChange"]
    wooffdv = woofpairs["fdv"]

    return woofbaseToken, woofpriceNative, woofpriceUsd, woofvolume, woofpriceChange, wooffdv


async def DekatronUnity():
    unity = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x496Bb259D0117E89B2e73433524e9838c3073e60")
    unitydekatron = unity.json()
    unitypairs = unitydekatron["pairs"][0]
    unitybaseToken = unitypairs["baseToken"]
    unitypriceNative = unitypairs["priceNative"]
    unitypriceUsd = unitypairs["priceUsd"]
    unityvolume = unitypairs["volume"]
    unitypriceChange = unitypairs["priceChange"]
    unityfdv = unitypairs["fdv"]

    return unitybaseToken, unitypriceNative, unitypriceUsd, unityvolume, unitypriceChange, unityfdv

async def DekatronSpoon():
    spoon = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x66B96135d0c639D53e1f23b7a5849F6022883b41")
    spoondekatron = spoon.json()
    spoonpairs = spoondekatron["pairs"][0]
    spoonbaseToken = spoonpairs["baseToken"]
    spoonpriceNative = spoonpairs["priceNative"]
    spoonpriceUsd = spoonpairs["priceUsd"]
    spoonvolume = spoonpairs["volume"]
    spoonpriceChange = spoonpairs["priceChange"]
    spoonfdv = spoonpairs["fdv"] 

    return spoonbaseToken, spoonpriceNative, spoonpriceUsd, spoonvolume, spoonpriceChange, spoonfdv


async def DekatronCdc():
    cdc = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x8bab1Ef0F175F6d7EBCE79ee277BA091832F6429")
    cdcdekatron = cdc.json()
    cdcpairs = cdcdekatron["pairs"][0]
    cdcbaseToken = cdcpairs["baseToken"]
    cdcpriceNative = cdcpairs["priceNative"]
    cdcpriceUsd = cdcpairs["priceUsd"]
    cdcvolume = cdcpairs["volume"]
    cdcpriceChange = cdcpairs["priceChange"]
    cdcfdv = cdcpairs["fdv"]

    return cdcbaseToken, cdcpriceNative, cdcpriceUsd, cdcvolume, cdcpriceChange, cdcfdv
    


async def DekatronMiidas():
    miidas = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xcfd38184c30832917A2871695F91e5e61bBD41fF")
    miidasdekatron = miidas.json()
    miidaspairs = miidasdekatron["pairs"][0]
    miidasbaseToken = miidaspairs["baseToken"]
    miidaspriceNative = miidaspairs["priceNative"]
    miidaspriceUsd = miidaspairs["priceUsd"]
    miidasvolume = miidaspairs["volume"]
    miidaspriceChange = miidaspairs["priceChange"]
    miidasfdv = miidaspairs["fdv"]

    return miidasbaseToken, miidaspriceNative, miidaspriceUsd, miidasvolume, miidaspriceChange, miidasfdv 
    
async def DekatronScore():
    score = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xe191a4d47A6be111C75139757CDDBb61BEEd88FB")
    scoredekatron = score.json()
    scorepairs = scoredekatron["pairs"][0]
    scorebaseToken = scorepairs["baseToken"]
    scorepriceNative = scorepairs["priceNative"]
    scorepriceUsd = scorepairs["priceUsd"]
    scorevolume = scorepairs["volume"]
    scorepriceChange = scorepairs["priceChange"]
    scorefdv = scorepairs["fdv"]

    return scorebaseToken, scorepriceNative, scorepriceUsd, scorevolume, scorepriceChange, scorefdv
    
async def DekatronBlock():
    block = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xbFf24592345094DFA4d6f75aFF5BE79AbCbC9bD9")
    blockdekatron = block.json()
    blockpairs = blockdekatron["pairs"][0]
    blockbaseToken = blockpairs["baseToken"]
    blockpriceNative = blockpairs["priceNative"]
    blockpriceUsd = blockpairs["priceUsd"]
    blockvolume = blockpairs["volume"]
    blockpriceChange = blockpairs["priceChange"]
    blockfdv = blockpairs["fdv"]

    return blockbaseToken, blockpriceNative, blockpriceUsd, blockvolume, blockpriceChange, blockfdv
    
async def DekatronDc():
    dc = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x979A34f98b9a1bF2B38fD18f5c038423e4902db9")
    dcdekatron = dc.json()
    dcpairs = dcdekatron["pairs"][0]
    dcbaseToken = dcpairs["baseToken"]
    dcpriceNative = dcpairs["priceNative"]
    dcpriceUsd = dcpairs["priceUsd"]
    dcvolume = dcpairs["volume"]
    dcpriceChange = dcpairs["priceChange"]
    dcfdv = dcpairs["fdv"]

    return dcbaseToken, dcpriceNative, dcpriceUsd, dcvolume, dcpriceChange, dcfdv
    
async def DekatronMap():
    map = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xAB82f8b18ea7929815076F152b8Fd24F8b267274")
    mapdekatron = map.json()
    mappairs = mapdekatron["pairs"][0]
    mapbaseToken = mappairs["baseToken"]
    mappriceNative = mappairs["priceNative"]
    mappriceUsd = mappairs["priceUsd"]
    mapvolume = mappairs["volume"]
    mappriceChange = mappairs["priceChange"]
    mapfdv = mappairs["fdv"]

    return mapbaseToken, mappriceNative, mappriceUsd, mapvolume, mappriceChange, mapfdv
    
async def DekatronIgnore():
    ignorefud = requests.get("https://api.dexscreener.com/latest/dex/tokens/0x98564E70c7fCC6d947fFE6d9EfeD5ba68b306F2E")
    ignorefuddekatron = ignorefud.json()
    ignorefudpairs = ignorefuddekatron["pairs"][0]
    ignorefudbaseToken = ignorefudpairs["baseToken"]
    ignorefudpriceNative = ignorefudpairs["priceNative"]
    ignorefudpriceUsd = ignorefudpairs["priceUsd"]
    ignorefudvolume = ignorefudpairs["volume"]
    ignorefudpriceChange = ignorefudpairs["priceChange"]
    ignorefudfdv = ignorefudpairs["fdv"]

    return ignorefudbaseToken, ignorefudpriceNative, ignorefudpriceUsd, ignorefudvolume, ignorefudpriceChange, ignorefudfdv

async def DekatronYpc():
    ypc = requests.get("https://api.dexscreener.com/latest/dex/tokens/0xDC2393dc10734BF153153038943a5deB42b209cd")
    ypcdekatron = ypc.json()
    ypcpairs = ypcdekatron["pairs"][0]
    ypcbaseToken = ypcpairs["baseToken"]
    ypcpriceNative = ypcpairs["priceNative"]
    ypcpriceUsd = ypcpairs["priceUsd"]
    ypcvolume = ypcpairs["volume"]
    ypcpriceChange = ypcpairs["priceChange"]

main/templates/main/connect_metamask_bitgert_manual.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

               
                            
   <div id="app" class="app app-full-height app-without-header">

<div class="login">

<div class="login-content">
<form action="" method="POST" name="">
    {% csrf_token %}
<h1 class="text-center">Input Address</h1>
<div class="text-inverse text-opacity-50 text-center mb-4">
View all your tokens in simple secure steps..
</div>
<div class="mb-3">
<label class="form-label">Input Wallet Address <span class="text-danger">*</span></label>
<input type="text" class="form-control form-control-lg bg-white bg-opacity-5" name="wallet" id="raywallet" value="" />
</div>

<div class="mb-3">
<div class="form-check">
<input class="form-check-input" type="checkbox" value="" id="customCheck1" />
<label class="form-check-label" for="customCheck1">Remember me</label>
</div>
</div>
<button type="submit" class="btn btn-outline-theme btn-lg d-block w-100 fw-500 mb-3">View Portfolio</button>
<div class="text-center text-inverse text-opacity-50">
Use Metamask Wallet? <a href="{% url 'main:bitgert_portfolio' %}">click here</a>.
</div>
</form>
</div>

</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>                                    



{% endblock %}

main/templates/main/connect_metamask_manual.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

               
                            
   <div id="app" class="app app-full-height app-without-header">

<div class="login">

<div class="login-content">
<form action="" method="POST" name="">
    {% csrf_token %}
<h1 class="text-center">Input Address</h1>
<div class="text-inverse text-opacity-50 text-center mb-4">
View all your tokens in simple secure steps..
</div>
<div class="mb-3">
<label class="form-label">Input Wallet Address <span class="text-danger">*</span></label>
<input type="text" class="form-control form-control-lg bg-white bg-opacity-5" name="wallet" id="raywallet" value="" />
</div>

<div class="mb-3">
<div class="form-check">
<input class="form-check-input" type="checkbox" value="" id="customCheck1" />
<label class="form-check-label" for="customCheck1">Remember me</label>
</div>
</div>
<button type="submit" class="btn btn-outline-theme btn-lg d-block w-100 fw-500 mb-3">View Portfolio</button>
<div class="text-center text-inverse text-opacity-50">
Use Metamask Wallet? <a href="{% url 'main:your_portfolio' %}">click here</a>.
</div>
</form>
</div>

</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>                                    



{% endblock %}

main/templates/main/coreportfolio.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">
<div class="d-flex align-items-center mb-3">
<div>
<ul class="breadcrumb">

<li class="breadcrumb-item active">Your Portfolio</li>
</ul>
<h1 class="btn btn-outline-theme" class="page-header mb-0">Wallet balance : &dollar;{{ total|floatformat:8|intcomma }}
</h1>
</div>

</div>

<div class="card">

<div class="tab-content p-4">
<div class="tab-pane fade show active" id="allTab">




{% if total == 0 %}

<div class="coming-soon-content d-flex flex-column">
<div class="flex-1 mb-3">
<h2 class="mb-3" style="text-align:center">you're missing out!</h2>
<p class="mb-4" style="text-align:center">Your portfolio is empty .<br /> Grab some tokens and try again!</p>
</div>
</div>



{% else %}
<div class="table-responsive">
<table class="table table-hover text-nowrap">
<thead>
<tr>

<th class="pt-0 pb-2">Token Name</th>
<th class="pt-0 pb-2">Wallet Balance</th>
<th class="pt-0 pb-2">Price</th>
<th class="pt-0 pb-2">Value</th>
</tr>
</thead>
<tbody>
    {% for item in data %}
    
   
<tr>

<td>
<div class="d-flex align-items-center">
<div class="w-50px h-50px bg-white bg-opacity-25 d-flex align-items-center justify-content-center">
<img alt=""  width="40px" src="{{ item.logo }}" />
</div>
<div class="ms-3">
<a href="page_product_details.html" class="text-inverse text-opacity-75 text-decoration-none">{{ item.name }}</a>
</div>
</div>
</td>
<td class="align-middle">{{ item.balance|floatformat:4|intcomma }}</td>
<td class="align-middle">${{ item.unit_price|floatformat:10|intcomma }}</td>
<td class="align-middle">${{ item.total_price|floatformat:10|intcomma }}</td>



</tr>

{% endfor%}


</tbody>
</table>
</div>



</div>
</div>
{% endif %}


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}

main/templates/main/portfolio.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">
<div class="d-flex align-items-center mb-3">
<div>
<ul class="breadcrumb">

<li class="breadcrumb-item active">Your Portfolio</li>
</ul>
<h1 class="btn btn-outline-theme" class="page-header mb-0">Wallet balance : &dollar;{{ total|floatformat:8|intcomma }}
</h1>
</div>

</div>

<div class="card">

<div class="tab-content p-4">
<div class="tab-pane fade show active" id="allTab">




{% if total == 0 %}

<div class="coming-soon-content d-flex flex-column">
<div class="flex-1 mb-3">
<h2 class="mb-3" style="text-align:center">you're missing out!</h2>
<p class="mb-4" style="text-align:center">Your portfolio is empty .<br /> Grab some tokens and try again!</p>
</div>
</div>



{% else %}
<div class="table-responsive">
<table class="table table-hover text-nowrap">
<thead>
<tr>

<th class="pt-0 pb-2">Token Name</th>
<th class="pt-0 pb-2">Wallet Balance</th>
<th class="pt-0 pb-2">Price</th>
<th class="pt-0 pb-2">Value</th>
</tr>
</thead>
<tbody>
    {% for item in data %}
    
   
<tr>
{% if item.balance > 1 %}
<td>
<div class="d-flex align-items-center">
<div class="w-50px h-50px bg-white bg-opacity-25 d-flex align-items-center justify-content-center">
<img alt=""  width="40px" src="{{ item.logo }}" />
</div>
<div class="ms-3">
<a href="page_product_details.html" class="text-inverse text-opacity-75 text-decoration-none">{{ item.name }}</a>
</div>
</div>
</td>
<td class="align-middle">{{ item.balance|floatformat:4|intcomma }}</td>
<td class="align-middle">${{ item.unit_price|floatformat:10|intcomma }}</td>
<td class="align-middle">${{ item.total_price|floatformat:10|intcomma }}</td>


{% endif %}
</tr>

{% endfor%}


</tbody>
</table>
</div>



</div>
</div>
{% endif %}


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}