curl_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("wallet/", include("wallet.urls")),
    path("app/", include("app_user.urls")),
    path("staking/", include("staking.urls")),
    path("launchpad/", include("launchpad.urls")),

]

handler404 = 'app_user.views.error_404'
handler500 = 'app_user.views.error_500'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'
handler404 = 'wallet.views.error_404'
handler500 = 'wallet.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

launchpad/urls.py
from django.urls import path
from . import views

app_name = "launchpad"

urlpatterns = [
	path("", views.IndexView, name="launchpad"),
    
	path("add-ido/", views.AddIdoView, name="add_ido"),
    path("fund-presale/<int:ido_id>/", views.FundPresaleView, name="fund_presale"),
	path("details/<int:ido_id>/", views.DetailsView, name="details"),
	path("contribute/<int:ido_id>/", views.ContributeView, name="contribute"),
    
    path("my-presales/", views.MyPresalesView, name="my_presales"),
    path("my-idos/", views.MyIdosView, name="my_idos"),
    path("my-contributions/", views.MyContributionsView, name="my_contributions"),
    
    path("claim/<int:ido_id>/", views.ClaimView, name="claim"),
    path("emergency-withdraw/<int:ido_id>/", views.EWithdrawView, name="e_withdraw"),
    path("end-presale/", views.EndPresaleView, name="end_presale"),

    path("withdraw-project-token/<int:ido_id>/", views.WithdrawPtView, name="withdraw_project_token"),
    path("withdraw-contributed-token/<int:ido_id>/", views.WithdrawCtView, name="withdraw_contributed_token"),


]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

    path("your-portfolio/manual/", views.ConnectMetamaskManualView, name="your_portfolio_manual"),
    path("your-portfolio/bitgert/", views.ConnectMetamaskManualBView, name="your_portfolio_bitgert"),
    path("your-portfolio/bsc/", views.ConnectMetamaskManualBscView, name="your_portfolio_bsc"),
    path("your-portfolio/canto/", views.ConnectMetamaskManualCantoView, name="your_portfolio_canto"),
    path("your-portfolio/core/", views.ConnectMetamaskManualCoreView, name="your_portfolio_core"),
    path("your-portfolio/", views.ConnectMetamaskView, name="your_portfolio"),
    path("bitgert-portfolio/", views.BitgertConnectMetamaskView, name="bitgert_portfolio"),
    path("bsc-portfolio/", views.BscConnectMetamaskView, name="bsc_portfolio"),
    path("canto-portfolio/", views.CantoConnectMetamaskView, name="canto_portfolio"),
    path("core-portfolio/", views.CoreConnectMetamaskView, name="core_portfolio"),
    path("portfolio/", views.PortfolioView, name="portfolio"),
    path("bscportfolio/", views.BscPortfolioView, name="bscportfolio"),
    path("brise-portfolio/", views.BrisePortfolioView, name="brise_portfolio"),
    path("wcanto-portfolio/", views.WCantoPortfolioView, name="wcanto_portfolio"),
    path("coreportfolio/", views.CorePortfolioView, name="coreportfolio"),
	path("", views.IndexView, name="index"),
	path("none/", views.NoneView, name="none"),
	path("doken/", views.DokenView, name="doken"),
	path("loop/", views.LoopView, name="loop"),
	path("candy/", views.CandyView, name="candy"),
	path("ice/", views.IceView, name="ice"),
	path("navis/", views.NavisView, name="navis"),
	path("bow/", views.BowView, name="bow"),
	path("lung/", views.LungView, name="lung"),
	path("bitgert/", views.BitgertView, name="bitgert"),
	path("canto/", views.CantoView, name="canto"),
	path("core/", views.CoreView, name="core"),
	path("coming/", views.ComingView, name="coming"),
	path("shadowswap/", views.ShadowView, name="shadowswap"),
	path("coreid/", views.CoreidView, name="coreid"),
	path("crest/", views.CrestView, name="crest"),
	path("yieldz/", views.YieldsView, name="yieldz"),
	path("happy/", views.HappyView, name="happy"),
	path("lfgswap/", views.LfgswapView, name="lfgswap"),
	path("4token/", views.IgnoreFudView, name="4token"),
	path("ypc/", views.YpcView, name="ypc"),
	path("3dc/", views.DcView, name="3dc"),
	path("aicore/", views.AicoreView, name="aicore"),
	path("ainu/", views.AinuView, name="ainu"),
	path("akio/", views.AkioView, name="akio"),
	path("bcore/", views.BcoreView, name="bcore"),
	path("block/", views.BlockView, name="block"),
	path("bitvexa/", views.BitvexaView, name="bitvexa"),
	path("hobo/", views.HoboView, name="hobo"),
	path("woof/", views.WoofView, name="woof"),
	path("word/", views.WordView, name="word"),
	path("score/", views.ScoreView, name="score"),
	path("cbunny/", views.CbunnyView, name="cbunny"),
	path("cshare/", views.CshareView, name="cshare"),
	path("ctomb/", views.CtombView, name="ctomb"),
	path("emperor/", views.EmperorView, name="emperor"),
	path("flash/", views.FlashView, name="flash"),
	path("green/", views.GreenView, name="green"),
	path("royale/", views.RoyaleView, name="royale"),
	path("miidas/", views.MiidasView, name="miidas"),
	path("unity/", views.UnityView, name="unity"),
	path("spoon/", views.SpoonView, name="spoon"),
	path("shield/", views.ShieldView, name="shield"),
	path("yfi/", views.YfiView, name="yfi"),
	path("pepe/", views.PepeView, name="pepe"),
	path("map/", views.MapView, name="map"),
	path("crystal/", views.CrystalView, name="crystal"),
	path("more/", views.MoreView, name="more"),
	path("coredoge/", views.CoredogeView, name="coredoge"),
	path('token/<str:token_id>/', views.token_details, name='token_details'),
	path('pool_info/<int:page>/', views.pool_info, name='pool_info'),
	path("tokens/<str:token_id>/", views.token_detail, name="token_detail"),
	

]

staking/urls.py
from django.urls import path
from . import views

app_name = "stake"

urlpatterns = [
	path("pools/<int:ido_id>/", views.IndexView, name="pool"),
	path("stake/<int:ido_id>/<int:amount>/", views.StakeView, name="stake"),
    path("my-stakes/", views.MyStakesView, name="my_stakes"),
	path("harvest/<int:stake_id>/", views.HarvestView, name="harvest"),
]

launchpad/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
import requests

from launchpad.models import *
from app_user.models import *

# Create your views here.


def CompareDatetimes(due_date):
	import pytz
	from datetime import datetime
	import datetime as dt
	utc = pytz.UTC
	#live datetime.now value might change
	#today_date = utc.localize(datetime.now())
	today_date = utc.localize(datetime.now()+ dt.timedelta(hours=1))
	due_date = due_date
		
	if today_date.replace(tzinfo=utc) >= due_date.replace(tzinfo=utc):
		running_status = False
	else:
		running_status = True

	print(running_status)
	print(today_date.replace(tzinfo=utc))
	print(due_date.replace(tzinfo=utc))
	print("shshdhdsdhshdshdshdhdhhsdhsdhshdhdhhshdhhd")

	return running_status


def AddIdoView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		listing_price = request.POST.get("listing_price")
		presale_price = request.POST.get("presale_price")

		token_address = request.POST.get("token_address")
		token_symbol = request.POST.get("token_symbol")

		total_supply = request.POST.get("total_supply")

		name = request.POST.get("name")
		description = request.POST.get("description")
		link = request.POST.get("link")
		soft_cap = request.POST.get("soft_cap")
		hard_cap = request.POST.get("hard_cap")

		tier0_min = request.POST.get("tier0_min")
		tier1_min = request.POST.get("tier1_min")
		tier2_min = request.POST.get("tier2_min")
		tier3_min = request.POST.get("tier3_min")

		tier0_max = request.POST.get("tier0_max")
		tier1_max = request.POST.get("tier1_max")
		tier2_max = request.POST.get("tier2_max")
		tier3_max = request.POST.get("tier3_max")

		whitelist_limit = request.POST.get("whitelist_limit")
		whitelist_start = request.POST.get("whitelist_start")
		whitelist_stop = request.POST.get("whitelist_stop")

		ido_start = request.POST.get("ido_start")
		ido_stop = request.POST.get("ido_stop")

		allocation_cf_liquidity = request.POST.get("allocation_cf_liquidity")
		allocation_cf_project = request.POST.get("allocation_cf_project")

		allocation_pt_liquidity = request.POST.get("allocation_pt_liquidity")
		allocation_pt_contributors = request.POST.get("allocation_pt_contributors")
		allocation_pt_project = request.POST.get("allocation_pt_project")

		vesting_duration = request.POST.get("vesting_duration")

		try:
			image = request.FILES["image"]
		except:
			image = None

		try:
			logo = request.FILES["logo"]
		except:
			logo = None

		ido = Ido.objects.create(app_user=app_user, listing_price=listing_price, presale_price=presale_price,
			   token_address=token_address, token_symbol=token_symbol, total_supply=total_supply,
			   name=name, description=description, link=link, soft_cap=soft_cap, hard_cap=hard_cap,
			tier0_min=tier0_min, tier1_min=tier1_min, tier2_min=tier2_min, tier3_min=tier3_min, 
			tier0_max=tier0_max, tier1_max=tier1_max, tier2_max=tier2_max, tier3_max=tier3_max,
			ido_start=ido_start, ido_stop=ido_stop, logo=logo, image=image,
			allocation_cf_liquidity=allocation_cf_liquidity, allocation_cf_project=allocation_cf_project,
			allocation_pt_liquidity=allocation_pt_liquidity, allocation_pt_contributors=allocation_pt_contributors, 
			allocation_pt_project=allocation_pt_project, vesting_duration=vesting_duration
			)
		ido.save()

		if whitelist_limit:
			ido.whitelist_limit = whitelist_limit
			ido.whitelist_start = whitelist_start
			ido.whitelist_stop = whitelist_stop
			ido.save()

		if ido:
			resp = requests.post("https://api.iotexchartapp.com/brise-create-wallet/", data={"username": app_user.user}).json()
			wallet_address = resp["public_key"]
			wallet_key = resp["private_key"]
			ido.wallet_address = wallet_address
			ido.wallet_address_key = wallet_key
			ido.save()

		messages.warning(request, "Ido Created")
		return HttpResponseRedirect(reverse("launchpad:fund_presale", args=[ido.id]))


	else:
		context = {"app_user": app_user}
		return render(request, "launchpad/add_ido.html", context )




def FundPresaleView(request, ido_id):
	ido = Ido.objects.get(id=ido_id)
	if request.method == "POST":
		pass


	else:
		context = {"ido": ido}
		return render(request, "launchpad/fund_presale.html", context )



def IndexView(request):
	if request.method == "POST":
		pass


	else:
		idos = Ido.objects.all().order_by('-pub_date')[0:10]
		context = {"idos": idos}
		return render(request, "launchpad/index.html", context )


def DetailsView(request, ido_id):
	if request.method == "POST":
		pass


	else:
		ido = Ido.objects.get(id=ido_id)

		#check for whitelist status
		if ido.whitelist_limit:

			#check if staking is running
			running_status = CompareDatetimes(ido.whitelist_stop)
		else:
			running_status = CompareDatetimes(ido.ido_stop)

		#inactive(using whitelist filling model)
		#if ido.stakes.count() >= int(ido.whitelist_limit):
		#	whitelisting = False
		#else:
		#	whitelisting = True

		context = {"ido": ido, "whitelisting": running_status}
		return render(request, "launchpad/details.html", context )


def WithdrawIdoFund(request, amount):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	sender = app_user.wallet_address
	sender_key = app_user.wallet_key
	receiver = "0x545486DE665fb131F21bbEB1B6CAF1973Fc5258f" 
	token = "abr"

	try:
		resp = requests.post("https://api.iotexchartapp.com/send-brise/", data={"sender":sender,"sender_key": sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
		txn_hash = resp["txn_hash"]
		
	except:
		txn_hash = None

	print(txn_hash)
	return txn_hash

def ContributeView(request, ido_id):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	ido = Ido.objects.get(id=ido_id)

	#getting the stake
	stake = None
	for item in ido.stakes.all():
		if item.app_user == app_user:
			stake = item
			break



	#generating the min and max for contribution
	if stake == None:
		tier_value = 0
		min_val = ido.tier0_min
		max_val = ido.tier0_max
	elif stake.amount == float(1):
		tier_value = 1
		min_val = ido.tier1_min
		max_val = ido.tier1_max
	elif stake.amount == float(2):
		tier_value = 2
		min_val = ido.tier2_min
		max_val = ido.tier2_max
	else:
		tier_value = 3
		min_val = ido.tier3_min
		max_val = ido.tier3_max

	if request.method == "POST":

		#check if user' contribution status
		contributed = False
		for item in ido.contributors.all():
			if item.wallet_address == app_user.wallet_address:
				contributed = True
				contributor = item
				break

		#check if user' whitelisted status
		whitelisted = False
		for item in ido.whitelist.all():
			if item.wallet_address == app_user.wallet_address:
				whitelisted = True
				white = item
				break
		
		if contributed == False and whitelisted == False:
			input_amount = float(request.POST.get("input_amount"))
			if WithdrawIdoFund(request, input_amount):
				output_amount = float(input_amount) * float(ido.presale_price)
				contributor = Contributor.objects.create(ido_id=ido.id, wallet_address=app_user.wallet_address, input_amount=input_amount,
							output_amount=output_amount)
				contributor.save()

				ic = IdoContributorConnector(ido=ido, contributor=contributor)
				ic.save()
			else:
				print("sorry withdrawal not sucessful")
				messages.warning(request, "Sorry, this is not successful")
				return HttpResponseRedirect(reverse("launchpad:launchpad"))

		elif whitelisted == True and contributed == False:
			input_amount = float(request.POST.get("input_amount"))
			if WithdrawIdoFund(request, input_amount):
				output_amount = float(input_amount) * float(ido.presale_price)
				white.input_amount += input_amount
				white.output_amount += output_amount

				#check for contribution cap(tier_max)
				if float(white.input_amount) + float(input_amount) > float(max_val):
					messages.warning(request, "Sorry, you will exceed your contribution limit")
					return HttpResponseRedirect(reverse("launchpad:launchpad"))
				
				else:
					white.save()

			else:
				print("sorry, this not sucessful")
				messages.warning(request, "Sorry, this is not successful")
				return HttpResponseRedirect(reverse("launchpad:launchpad"))

		elif contributed == True and whitelisted == False:
			
			input_amount = float(request.POST.get("input_amount"))
			if WithdrawIdoFund(request, input_amount):
				output_amount = float(input_amount) * float(ido.presale_price)
				contributor.input_amount += input_amount
				contributor.output_amount += output_amount

				#check for contribution cap(tier_max)
				if float(contributor.input_amount) + float(input_amount) > float(ido.tier0_max):
					messages.warning(request, "Sorry, you will exceed your contribution limit")
					return HttpResponseRedirect(reverse("launchpad:launchpad"))
				
				else:
					contributor.save()
			else:
				print("sorry not sucessfull")
				messages.warning(request, "Sorry, this is not successful")
				return HttpResponseRedirect(reverse("launchpad:launchpad"))

		else:
			input_amount = float(request.POST.get("input_amount"))
			if WithdrawIdoFund(request, input_amount):
				output_amount = float(input_amount) * float(ido.presale_price)
				white = White.objects.create(ido_id=ido.id, wallet_address=app_user.wallet_address, input_amount=input_amount,
							output_amount=output_amount)
				white.save()

				iw = IdoWhiteConnector(ido=ido, white=white)
				iw.save()

			else:
				print("sorry not sucess")
				messages.warning(request, "Sorry, this is not successful")
				return HttpResponseRedirect(reverse("launchpad:launchpad"))


		messages.warning(request, "Contribution completed!")
		return HttpResponseRedirect(reverse("launchpad:launchpad"))



	else:


		if ido.whitelist_limit:

launchpad/templates/launchpad/index.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">

<div class="mailbox">

<div class="mailbox-toolbar">
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:add_ido' %}" class="mailbox-toolbar-link text-white bg-white bg-opacity-15">Add IDOs <i class="fa fa-pen fs-12px ms-1"></i></a></div>
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:my_idos' %}" class="mailbox-toolbar-link text-white bg-white bg-opacity-15">My IDOs <i class="fa fa-pen fs-12px ms-1"></i></a></div>
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:my_contributions' %}" class="mailbox-toolbar-link text-white bg-success bg-opacity-15">My Contributions<i class="fa fa-wallet fs-12px ms-1"></i></a></div>
</div>

</div>



<div id="app" class="app app-content-full-height app-without-sidebar app-without-header">


<div class="pos " id="pos">





<div class="">
<div class=" h-100 p-3" data-scrollbar="true" data-height="100%">
<div class="row gx-3">
    <h4 class="page-header">All IDOs</h4>

{% if idos %}

{% for item in idos %}
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pb-3">
    <div class="card h-100">
    <div class="card-body h-100 p-1">
    <div class="pos-product">
    <div class="img" style="background-image: url({{ item.image.url }})"></div>
    <div class="info">
    <div class="title text-truncate" style="display:flex; justify-content: space-between;">
        <div>{{ item.name }} <span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="bi bi-patch-check fs-9px fa-fw me-5px"></i> Verified</span></div>
        <img width="30px" src="{{ item.logo.url }}">
    </div>
    <br>
    <div class=" flex-1">

    <div class="mb-2 fs-5 text-truncate">Progress: 60.04%</div>
    <div class="progress h-3px bg-white-transparent-2 mb-1" style="height: 20px !important;">
    <div class="progress-bar bg-theme" style="width: 60%;"></div>
    </div>
    <div class="fs-11px text-white text-opacity-50 mb-2 text-truncate">
    {{ item.pub_date }}
    </div>

    </div>

    <div class="d-flex align-items-center mb-3">
    <div class="w-100px">Availability:</div>
    <div class="flex-1">
    <div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" name="qty" id="product1" checked value="1" />
    <label class="form-check-label" for="product1"></label>
    </div>
    </div>
    </div>
    <div>
    <a href="{% url 'launchpad:contribute' item.id %}" class="btn btn-success d-block mb-2"><i class="fa fa-check fa-fw"></i>In Progress</a>
    <a href="{% url 'launchpad:details' item.id %}" class="btn btn-default d-block"><i class="fa fa-check fa-fw"></i> Details</a>
    </div>
    </div>
    </div>
    </div>
    <div class="card-arrow">
    <div class="card-arrow-top-left"></div>
    <div class="card-arrow-top-right"></div>
    <div class="card-arrow-bottom-left"></div>
    <div class="card-arrow-bottom-right"></div>
    </div>
    </div>
    </div>

    {% endfor %}
{% else %}

<p>Sorry, no idos yet</p>

{% endif %}



</div>


<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>

</div>

</div>
</div>




</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}

launchpad/templates/launchpad/my_contributions.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">
    <div class="d-flex align-items-center mb-3">

        <a href="{% url 'launchpad:add_ido' %}">Add Ido</a>
    
    </div>
    
    <div class="d-flex align-items-center mb-3">
    
        <a href="{% url 'launchpad:launchpad' %}">All Idos</a>
    
    </div>
    
    <div class="d-flex align-items-center mb-3">
    
        <a href="{% url 'launchpad:my_idos' %}">My Idos</a>
    
    </div>
    
    <div class="d-flex align-items-center mb-3">
    
        <a href="{% url 'launchpad:my_contributions' %}">My Contributions</a>
    
    </div>


    {% if result %}
        {% for item in result %}
            <small>ido: {{ item.ido.name }}</small><br />
            <small>contribution: {{ item.contribution.input_amount }} core</small><br />
            <small>reward: {{ item.contribution.output_amount }} {{ item.ido.name }}</small><br />
            <small>Presale started: {{ item.ido.ido_start }}</small><br />
            <small>Presale will end: {{ item.ido.ido_stop }}</small><br />
            <a href="{% url 'launchpad:claim' item.ido.id %}">Claim Reward</a>
            <a href="{% url 'launchpad:details' item.ido.id %}">View Ido</a>
            <a href="{% url 'launchpad:contribute' item.ido.id %}">Add to Contribution</a>
            <a href="{% url 'launchpad:e_withdraw' item.ido.id %}">Emergency Withdraw</a>
            <hr>
        {% endfor %}

    {% else %}
        <p>Sorry, no contributions found.</p>
    {% endif %}



{% endblock %}

launchpad/templates/launchpad/my_idos.html
{% extends "main/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}

<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>


<div id="content" class="app-content">

<div class="mailbox">

<div class="mailbox-toolbar">
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:launchpad' %}" class="mailbox-toolbar-link text-white bg-white bg-opacity-15">All IDOs <i class="fa fa-pen fs-12px ms-1"></i></a></div>
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:add_ido' %}" class="mailbox-toolbar-link text-white bg-white bg-opacity-15">Add IDOs <i class="fa fa-pen fs-12px ms-1"></i></a></div>
<div class="mailbox-toolbar-item"><a href="{% url 'launchpad:my_contributions' %}" class="mailbox-toolbar-link text-white bg-success bg-opacity-15">My Contributions<i class="fa fa-wallet fs-12px ms-1"></i></a></div>
</div>

</div>




<div id="app" class="app app-content-full-height app-without-sidebar app-without-header">


<div class="pos " id="pos">





<div class="">
<div class=" h-100 p-3" data-scrollbar="true" data-height="100%">
<div class="row gx-3">

{% if idos %}

{% for item in idos %}
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 pb-3">
    <div class="card h-100">
    <div class="card-body h-100 p-1">
    <div class="pos-product">
    <div class="img" style="background-image: url({{ item.image.url }})"></div>
    <div class="info">
    <div class="title text-truncate" style="display:flex; justify-content: space-between;">
        <div>{{ item.name }} <span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="bi bi-patch-check fs-9px fa-fw me-5px"></i> Verified</span></div>
        <img width="30px" src="{{ item.logo.url }}">
    </div>
    <br>
    <div class=" flex-1">

    <div class="mb-2 fs-5 text-truncate">Progress: 60.04%</div>
    <div class="progress h-3px bg-white-transparent-2 mb-1" style="height: 20px !important;">
    <div class="progress-bar bg-theme" style="width: 60%;"></div>
    </div>
    <div class="fs-11px text-white text-opacity-50 mb-2 text-truncate">
    {{ item.pub_date }}
    </div>

    </div>

    <div class="d-flex align-items-center mb-3">
    <div class="w-100px">Availability:</div>
    <div class="flex-1">
    <div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" name="qty" id="product1" checked value="1" />
    <label class="form-check-label" for="product1"></label>
    </div>
    </div>
    </div>
    <div>
    <a href="#">Withdraw Allocation({{ item.token_symbol }}): Project Tokens</a>
    <br />  <br />
    <a href="#">Withdraw Allocation(curl): Contributed Tokens</a>
    <br />  <br />
    <a href="{% url 'launchpad:details' item.id %}" class="btn btn-default d-block"><i class="fa fa-check fa-fw"></i> Details</a>
    </div>
    </div>
    </div>
    </div>
    <div class="card-arrow">
    <div class="card-arrow-top-left"></div>
    <div class="card-arrow-top-right"></div>
    <div class="card-arrow-bottom-left"></div>
    <div class="card-arrow-bottom-right"></div>
    </div>
    </div>
    </div>

    {% endfor %}
{% else %}

<p>Sorry, no idos yet</p>

{% endif %}



</div>


<div class="card-arrow">
<div class="card-arrow-top-left"></div>
<div class="card-arrow-top-right"></div>
<div class="card-arrow-bottom-left"></div>
<div class="card-arrow-bottom-right"></div>
</div>

</div>

</div>
</div>




</div>


<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>


{% endblock %}